logLevel: debug
cleanupInterval: 10m
namespace:
  prefix: "tenama"
  suffix: "" # if not set tenama will use a random string instead
  duration: "168h" #7 days
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
      storage: "1Gi"
#    limits:
#      cpu: "1000m"
#      memory: "1Gi"

basicAuth:
  - username: user1
    password: user1
  - username: user2
    password: user2
