apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenama
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups: #allow to bind admin role to give oneself admin rights in the created namespace
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  resourceNames:
  - admin
  - edit
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
