apiVersion: v1
kind: Secret
metadata:
  name: tenama-config
  namespace: tenama-system
type: Opaque
data:
  config.yaml: bG9nTGV2ZWw6IGRlYnVnCmNsZWFudXBJbnRlcnZhbDogMTBtCm5hbWVzcGFjZToKICBwcmVmaXg6ICJ0ZW5hbWEiCiAgc3VmZml4OiAiIiAjIGlmIG5vdCBzZXQgdGVuYW1hIHdpbGwgdXNlIGEgcmFuZG9tIHN0cmluZyBpbnN0ZWFkCiAgZHVyYXRpb246ICIxNjhoIiAjNyBkYXlzCiAgcmVzb3VyY2VzOgogICAgcmVxdWVzdHM6CiAgICAgIGNwdTogIjEwMDBtIgogICAgICBtZW1vcnk6ICIxR2kiCiAgICAgIHN0b3JhZ2U6ICIxR2kiCiMgICAgbGltaXRzOgojICAgICAgY3B1OiAiMTAwMG0iCiMgICAgICBtZW1vcnk6ICIxR2kiCgpiYXNpY0F1dGg6CiAgLSB1c2VybmFtZTogdXNlcjEKICAgIHBhc3N3b3JkOiB1c2VyMQ==

