apiVersion: v1
kind: Service
metadata:
  labels:
    app: tenama
  name: tenama
  namespace: tenama-system
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: tenama
  sessionAffinity: None
  type: ClusterIP

